-- Create profiles table
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create walks table (Programmed Bookings)
CREATE TABLE walks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  walk_date DATE NOT NULL,
  assigned_user_id UUID REFERENCES profiles(id),
  start_time TIME NOT NULL,
  end_time TIME,
  notes TEXT,
  reminder_enabled BOOLEAN DEFAULT FALSE,
  reminder_minutes_before INTEGER DEFAULT 30,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create walk_sessions table for live tracking and real data
CREATE TABLE walk_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  walk_id BIGINT REFERENCES walks(id) ON DELETE SET NULL,
  started_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  ended_at TIMESTAMP WITH TIME ZONE,
  duration_minutes INTEGER,
  is_active BOOLEAN DEFAULT TRUE,
  source TEXT DEFAULT 'timer', -- 'booking', 'timer', 'manual'
  is_manual BOOLEAN DEFAULT FALSE,
  start_lat DOUBLE PRECISION,
  start_lng DOUBLE PRECISION,
  end_lat DOUBLE PRECISION,
  end_lng DOUBLE PRECISION,
  distance_meters DOUBLE PRECISION,
  tracking_enabled BOOLEAN DEFAULT FALSE,
  created_by UUID REFERENCES profiles(id) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Create walk_locations table for GPS tracking
CREATE TABLE walk_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  walk_session_id BIGINT REFERENCES walk_sessions(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id),
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  accuracy DOUBLE PRECISION,
  recorded_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE walks ENABLE ROW LEVEL SECURITY;
ALTER TABLE walk_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE walk_locations ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone" ON profiles
  FOR SELECT USING (true);

CREATE POLICY "Users can update own profile" ON profiles
  FOR UPDATE USING (auth.uid() = id);

-- Walks Policies
CREATE POLICY "Walks are viewable by everyone" ON walks
  FOR SELECT USING (true);

CREATE POLICY "Authenticated users can insert walks" ON walks
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update walks" ON walks
  FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can delete walks" ON walks
  FOR DELETE USING (auth.role() = 'authenticated');

-- Walk Sessions Policies
CREATE POLICY "Walk sessions are viewable by everyone" ON walk_sessions
  FOR SELECT USING (true);

CREATE POLICY "Authenticated users can insert walk sessions" ON walk_sessions
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update their own walk sessions" ON walk_sessions
  FOR UPDATE USING (auth.uid() = created_by);

-- Walk Locations Policies
CREATE POLICY "Walk locations are viewable by everyone" ON walk_locations
  FOR SELECT USING (true);

CREATE POLICY "Authenticated users can insert walk locations" ON walk_locations
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Function to handle new user profiles
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name)
  VALUES (new.id, new.raw_user_meta_data->>'full_name');
  RETURN new;
END;
$$ LANGUAGE PLPGSQL SECURITY DEFINER;

-- Trigger for new user
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
